function A = compute_dh_matrix(r, alpha, d, theta)

    rotz = [ cos(theta) -sin(theta) 0 0; ...
             sin(theta) cos(theta) 0 0 ; ...
             0 0 1 0; ...
             0 0 0 1 ]

    rotx = [ 1 0 0 0; ...
             0 cos(alpha) -sin(alpha) 0; ...
             0 sin(alpha) cos(alpha) 0; ...
             0 0 0 1]

    transz = [ 1 0 0 0; ...
               0 1 0 0; ...
               0 0 1 d; ...
               0 0 0 1 ]

    transx = [ 1 0 0 r; ...
               0 1 0 0; ...
               0 0 1 0; ...
               0 0 0 1]

    A = rotz*transz*transx*rotx;
end

